name: Eudaimonia
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          docker login --password $DOCKER_HUB_TOKEN --username spacez320
          docker build --tag spacez320/eudaimonia:latest .
          docker push spacez320/eudaimonia:latest
